add en cilium-speedup
DaoCloud/DaoCloud-docs pull request #2076
Opened 2023-08-08 10:23 UTC by Jeanine-tw

2023-08-08 12:56 UTC, windsonsea reviewed
yaml 代码段 要标记出来，不要全部用 bash

2023-08-08 12:56 UTC, windsonsea commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```bash
```suggestion
    ```yaml
```

2023-08-08 12:56 UTC, windsonsea commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```bash
```suggestion
    ```yaml
```

2023-08-08 12:56 UTC, windsonsea commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```bash
```suggestion
    ```yaml
```

2023-08-08 12:56 UTC, windsonsea commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```bash
```suggestion
    ```yaml
```

2023-08-08 12:56 UTC, windsonsea commented on docs/zh/docs/network/modules/cilium/cilium-speedup.md
>      ```bash
```suggestion
    ```yaml
```

2023-08-09 02:13 UTC, Jeanine-tw commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```bash
全部已修改

2023-08-09 02:38 UTC, Michelle951 approved these changes

2023-08-09 02:42 UTC, windsonsea requested changes
汗，不要全局替换呀，你得知道是什么代码

2023-08-09 02:42 UTC, windsonsea commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```yaml
```suggestion
    ```bash
```

2023-08-09 02:44 UTC, windsonsea commented
You can ask chatGPT for which language it is:

<img width="1154" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/79828097/cad2b01f-392e-4429-9edc-5bc3f5f95ece">

2023-08-09 03:17 UTC, Jeanine-tw commented on docs/en/docs/network/modules/cilium/cilium-speedup.md
> +    ```yaml
已修改

2023-08-09 03:22 UTC, windsonsea approved these changes

2023-08-09 03:36 UTC, merged