updated insight about otel
DaoCloud/DaoCloud-docs pull request #257
Opened 2022-10-17 09:24 UTC by windsonsea

Fix alignment and keep consistent style with other pages

@JaredTan95 
把这几篇放 最佳实践 怎么样

2022-10-17 09:30 UTC, JaredTan95 commented
内部讨论过了，就放在quckstart /installagent 后面

2022-10-17 09:30 UTC, JaredTan95 approved these changes

2022-10-17 09:46 UTC, JaredTan95 requested changes

2022-10-17 09:46 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
> +- opentelemetry-operator-controller-manager-xxx 以及 insight-agent-opentelemetry-collector- xxx 这两个 Pod 是否已准备就绪？
```suggestion
- deployment/opentelemetry-operator-controller-manager 和 deployment/insight-agent-opentelemetry-collector 对应的 Pod 已经准备就绪？
```

2022-10-17 09:46 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md
> +- opentelemetry-operator-controller-manager-xxx 以及 insight-agent-opentelemetry-collector- xxx 这两个 Pod 是否已准备就绪？
```suggestion
- deployment/opentelemetry-operator-controller-manager 和 deployment/insight-agent-opentelemetry-collector 对应的 Pod 已经准备就绪？
```

2022-10-17 09:49 UTC, JaredTan95 requested changes

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```yaml
```suggestion
```bash
kubectl apply -f - <<EOF
```

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```
```suggestion
EOF
```
```

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```
```suggestion
EOF
```
```

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```yaml
```suggestion
```bash
kubectl apply -f - <<EOF
```

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/navigation.yml
> +              - 通过 Operator 实现应用程序无侵入增强: insight/06UserGuide/01quickstart/otel/operator.md
```suggestion

```

2022-10-17 09:49 UTC, JaredTan95 commented on docs/zh/navigation.yml
>                - 安装 insight-agent 采集数据: insight/06UserGuide/01quickstart/installagent.md
```suggestion
              - 安装 insight-agent 采集数据: insight/06UserGuide/01quickstart/installagent.md
              - 使用 Opentelemetry 让你的应用具备可观测性: insight/06UserGuide/01quickstart/otel/otel.md
```

2022-10-17 09:58 UTC, JaredTan95 requested changes

2022-10-17 09:58 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```
在 ``` 上一行加上 `EOF`,

2022-10-17 09:58 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
>  ```
在 ``` 上一行加上 `EOF`

2022-10-17 10:05 UTC, JaredTan95 requested changes

2022-10-17 10:05 UTC, JaredTan95 commented on docs/zh/navigation.yml
> +                - 通过 Operator 实现应用程序无侵入增强: insight/06UserGuide/01quickstart/otel/operator.md
```suggestion
              - 使用 OpenTelemetry 让应用具备可观测性: insight/06UserGuide/01quickstart/otel/otel.md
                - 通过 Operator 实现应用程序无侵入增强: insight/06UserGuide/01quickstart/otel/operator.md
                - 使用 OpenTelemetry SDK 增强 Go 应用程序: insight/06UserGuide/01quickstart/otel/golang.md
                - 使用 OpenTelemetry SDK 为应用程序暴露指标: insight/06UserGuide/01quickstart/otel/meter.md
                - 使用 OpenTelemetry 自动探针增强 Go 应用程序: insight/06UserGuide/01quickstart/otel/golang-ebpf.md
                
```

2022-10-17 10:05 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md
> +# 使用 OpenTelemetry 自动探针增强 Go 应用
```suggestion
#  【实验性功能】使用 OpenTelemetry 自动探针增强 Go 应用
```

2022-10-17 10:18 UTC, Michelle951 approved these changes

2022-10-17 12:26 UTC, JaredTan95 requested changes

2022-10-17 12:26 UTC, JaredTan95 commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md
>  ```yaml
改成这样会方便用户使用一些：
```bash
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: insight-opentelemetry-autoinstrumentation
  namespace: insight-system
spec:
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentationspecresource
  resource:
    addK8sUIDAttributes: true
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317
  sampler:
    # Enum: always_on, always_off, traceidratio, parentbased_always_on, parentbased_always_off, parentbased_traceidratio, jaeger_remote, xray
    type: always_on
  java:
    image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.17.0
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
      - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
        value: "true"
      - name: SPLUNK_PROFILER_ENABLED
        value: "false"
  nodejs:
    image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.31.0
  python:
    image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.34b0
  dotnet:
    image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.3.1-beta.1
EOF

2022-10-17 13:01 UTC, windsonsea commented on docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md
>  ```yaml
这个已修改，其他几个 code block 是不是也要修改的

2022-10-18 01:35 UTC, JaredTan95 requested changes

2022-10-18 01:35 UTC, JaredTan95 commented on docs/zh/navigation.yml
> +                - 通过 Operator 实现应用程序无侵入增强: insight/06UserGuide/01quickstart/otel/operator.md
```suggestion
                - 通过 Operator 实现应用程序无侵入增强: insight/06UserGuide/01quickstart/otel/operator.md
                - 使用 OpenTelemetry SDK 增强 Go 应用程序: insight/06UserGuide/01quickstart/otel/golang.md
                - 使用 OpenTelemetry SDK 为应用程序暴露指标: insight/06UserGuide/01quickstart/otel/meter.md
                - 使用 OpenTelemetry 自动探针增强 Go 应用程序: insight/06UserGuide/01quickstart/otel/golang-ebpf.md
```

2022-10-18 01:42 UTC, JaredTan95 approved these changes

2022-10-18 02:01 UTC, merged